# Python Crash Course Part 3 Feature Selection & Split
### This is meant for internal usage, not for commercial purpose
### Timothy CL Lam 2017 DEC

In [77]:
import pandas as pd
import numpy as np
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

In [1]:
# The code was removed by DSX for sharing.

CHURN Gender Status  Children  Est Income Car Owner        Age  \
0     T      F      S       1.0    38000.00         N  24.393333   
1     F      M      M       2.0    29616.00         N  49.426667   
2     F      M      M       0.0    19732.80         N  50.673333   
3     F      M      S       2.0       96.33         N  56.473333   
4     F      F      M       2.0    52004.80         N  25.140000   

   LongDistance  International   Local  Dropped Paymethod LocalBilltype  \
0         23.56            0.0  206.08      0.0        CC        Budget   
1         29.78            0.0   45.50      0.0        CH     FreeLocal   
2         24.81            0.0   22.44      0.0        CC     FreeLocal   
3         26.13            0.0   32.88      1.0        CC        Budget   
4          5.03            0.0   23.11      0.0        CH        Budget   

  LongDistanceBilltype   Usage  RatePlan  
0       Intnl_discount  229.64       3.0  
1             Standard   75.29       2.0  
2             Standard   47.25       3.0  
3             Standard   59.01       1.0  
4       Intnl_discount   28.14       1.0

In [2]:
numerical_columns = list(df1.select_dtypes(include=[np.number]).columns)
categorical_columns = list(df1.select_dtypes(include=[object]).columns)
date_columns = list(df1.select_dtypes(include=['<M8[ns]']).columns)

NameError: name 'np' is not defined

In [80]:
from collections import defaultdict, Counter

In [81]:
columns_to_drop = []

# For categorical variables with more than that many values, we only keep the most frequent ones
LIMIT_DUMMIES = 100

# Only keep the top 100 values
def select_dummy_values(train, features):
    dummy_values = {}
    for feature in features:
        values = [
            value
            for (value, _) in Counter(train[feature]).most_common(LIMIT_DUMMIES)
        ]
        dummy_values[feature] = values
    return dummy_values

DUMMY_VALUES = select_dummy_values(df1, [x for x in categorical_columns if not x in columns_to_drop])


def dummy_encode_dataframe(df1):
    for (feature, dummy_values) in DUMMY_VALUES.items():
        for dummy_value in dummy_values:
            dummy_name = u'%s_value_%s' % (feature, dummy_value.decode('utf-8'))
            df1[dummy_name] = (df1[feature] == dummy_value).astype(float)
        del df1[feature]
        print 'Dummy-encoded feature %s' % feature

dummy_encode_dataframe(df1)

Dummy-encoded feature Status
Dummy-encoded feature Paymethod
Dummy-encoded feature Gender
Dummy-encoded feature Car Owner
Dummy-encoded feature LongDistanceBilltype
Dummy-encoded feature CHURN
Dummy-encoded feature LocalBilltype


In [82]:
df1.head()

Children  Est Income        Age  LongDistance  International   Local  \
0       1.0    38000.00  24.393333         23.56            0.0  206.08   
1       2.0    29616.00  49.426667         29.78            0.0   45.50   
2       0.0    19732.80  50.673333         24.81            0.0   22.44   
3       2.0       96.33  56.473333         26.13            0.0   32.88   
4       2.0    52004.80  25.140000          5.03            0.0   23.11   

   Dropped   Usage  RatePlan  Status_value_M              ...                \
0      0.0  229.64       3.0             0.0              ...                 
1      0.0   75.29       2.0             1.0              ...                 
2      0.0   47.25       3.0             1.0              ...                 
3      1.0   59.01       1.0             0.0              ...                 
4      0.0   28.14       1.0             1.0              ...                 

   Gender_value_F  Gender_value_M  Car Owner_value_N  Car Owner_value_Y  \
0             1.0             0.0                1.0                0.0   
1             0.0             1.0                1.0                0.0   
2             0.0             1.0                1.0                0.0   
3             0.0             1.0                1.0                0.0   
4             1.0             0.0                1.0                0.0   

   LongDistanceBilltype_value_Standard  \
0                                  0.0   
1                                  1.0   
2                                  1.0   
3                                  1.0   
4                                  0.0   

   LongDistanceBilltype_value_Intnl_discount  CHURN_value_F  CHURN_value_T  \
0                                        1.0            0.0            1.0   
1                                        0.0            1.0            0.0   
2                                        0.0            1.0            0.0   
3                                        0.0            1.0            0.0   
4                                        1.0            1.0            0.0   

   LocalBilltype_value_Budget  LocalBilltype_value_FreeLocal  
0                         1.0                            0.0  
1                         0.0                            1.0  
2                         0.0                            1.0  
3                         1.0                            0.0  
4                         1.0                            0.0  

[5 rows x 25 columns]

In [83]:
cols = list(df1)
# move the column to head of list using index, pop and insert
cols.insert(0, cols.pop(cols.index('CHURN_value_T')))
cols


[u'CHURN_value_T',
 'Children',
 'Est Income',
 'Age',
 'LongDistance',
 'International',
 'Local',
 'Dropped',
 'Usage',
 'RatePlan',
 u'Status_value_M',
 u'Status_value_S',
 u'Status_value_D',
 u'Paymethod_value_CC',
 u'Paymethod_value_Auto',
 u'Paymethod_value_CH',
 u'Gender_value_F',
 u'Gender_value_M',
 u'Car Owner_value_N',
 u'Car Owner_value_Y',
 u'LongDistanceBilltype_value_Standard',
 u'LongDistanceBilltype_value_Intnl_discount',
 u'CHURN_value_F',
 u'LocalBilltype_value_Budget',
 u'LocalBilltype_value_FreeLocal']

In [84]:
df1 = df1.ix[:, cols]
df1.drop('CHURN_value_F',1)
df1.rename(columns={'CHURN_value_T': 'Churn'}, inplace=True)

/usr/local/src/bluemix_jupyter_bundle.v71/notebook/lib/python2.7/site-packages/ipykernel/__main__.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  if __name__ == '__main__':


In [85]:
array = df1.values
x = array[:,1:25]
y = array[:,0]

In [86]:
x[:]

array([[  1.00000000e+00,   3.80000000e+04,   2.43933330e+01, ...,
          0.00000000e+00,   1.00000000e+00,   0.00000000e+00],
       [  2.00000000e+00,   2.96160000e+04,   4.94266670e+01, ...,
          1.00000000e+00,   0.00000000e+00,   1.00000000e+00],
       [  0.00000000e+00,   1.97328000e+04,   5.06733330e+01, ...,
          1.00000000e+00,   0.00000000e+00,   1.00000000e+00],
       ..., 
       [  0.00000000e+00,   8.38919000e+04,   6.10200000e+01, ...,
          0.00000000e+00,   1.00000000e+00,   0.00000000e+00],
       [  2.00000000e+00,   2.82208000e+04,   3.87666670e+01, ...,
          0.00000000e+00,   0.00000000e+00,   1.00000000e+00],
       [  0.00000000e+00,   2.85891000e+04,   1.56000000e+01, ...,
          0.00000000e+00,   0.00000000e+00,   1.00000000e+00]])

In [87]:
y[:]

array([ 1.,  0.,  0., ...,  1.,  1.,  1.])

### Chi Square Test 

In [88]:
#feature extraction 
test = SelectKBest(score_func=chi2, k=4)
fit = test.fit(x,y)
#summarize score
print (fit.scores_)



[  1.12820793e+02   9.74480451e+05   8.85022284e+00   4.35573208e+02
   1.24628119e+02   9.15789005e+02   1.54643145e+01   1.03031501e+03
   5.83161319e-02   1.15331241e+02   1.76246885e+02   6.08165207e-01
   4.95382522e+00   2.11138523e+01   9.99316613e-01   8.74364055e+00
   1.53421746e+01   8.84519247e-02   1.62566862e-01   6.72168068e+00
   1.50107016e+01   8.41000000e+02   6.77774997e-03   8.11887922e-03]


In [89]:
features = fit.transform(x)
print features[0:5,:]

[[  3.80000000e+04   2.06080000e+02   2.29640000e+02   0.00000000e+00]
 [  2.96160000e+04   4.55000000e+01   7.52900000e+01   1.00000000e+00]
 [  1.97328000e+04   2.24400000e+01   4.72500000e+01   1.00000000e+00]
 [  9.63300000e+01   3.28800000e+01   5.90100000e+01   1.00000000e+00]
 [  5.20048000e+04   2.31100000e+01   2.81400000e+01   1.00000000e+00]]


In [90]:
features.shape

(2066, 4)

### Recursive Feature Elimination (RFE)
The Recursive Feature Elimination (or RFE) works by recursively removing attributes and
building a model on those attributes that remain. It uses the model accuracy to identify which attributes (and combination of attributes) contribute the most to predicting the target attribute.
You can learn more about the RFE class3 in the scikit-learn documentation. The example below
uses RFE with the logistic regression algorithm to select the top 3 features. The choice of
algorithm does not matter too much as long as it is skillful and consistent.

In [91]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2066 entries, 0 to 2065
Data columns (total 25 columns):
Churn                                        2066 non-null float64
Children                                     2066 non-null float64
Est Income                                   2066 non-null float64
Age                                          2066 non-null float64
LongDistance                                 2066 non-null float64
International                                2066 non-null float64
Local                                        2066 non-null float64
Dropped                                      2066 non-null float64
Usage                                        2066 non-null float64
RatePlan                                     2066 non-null float64
Status_value_M                               2066 non-null float64
Status_value_S                               2066 non-null float64
Status_value_D                               2066 non-null float64
Paymethod_value_CC    

In [92]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
rfe = RFE(model, 3)
fit = rfe.fit(x, y)
print("Num Features: %d" % fit.n_features_)
print("Selected Features: %s" % fit.support_)
print("Feature Ranking: %s" % fit.ranking_)

Num Features: 3
Selected Features: [False False False False False False False False False False False False
 False False False False False False False False False  True  True  True]
Feature Ranking: [11 22 19 14 13 15 17 16 12 21  4 20  7 18  8  6  5  2  3  9 10  1  1  1]


### PCA
Principal Component Analysis (or PCA) uses linear algebra to transform the dataset into a
compressed form. Generally this is called a data reduction technique. A property of PCA is that
you can choose the number of dimensions or principal components in the transformed result. In
the example below, we use PCA and select 3 principal components. Learn more about the PCA
class in scikit-learn by reviewing the API4.

In [93]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
fit = pca.fit(x)
# summarize components
print("Explained Variance: %s" % fit.explained_variance_ratio_)
print(fit.components_)

Explained Variance: [  9.99992470e-01   7.15351882e-06   2.28254757e-07]
[[ -3.15033677e-06   9.99999961e-01   8.05916005e-05  -2.54535748e-05
    3.31818376e-06  -1.85252185e-04   4.75954444e-07  -1.91406548e-04
    9.16087850e-07   1.85405988e-06  -2.00665132e-06   1.52591441e-07
    3.88778338e-08  -1.99782827e-07   1.60904993e-07  -1.42997136e-06
    1.42997136e-06  -1.55170623e-06   1.55170623e-06  -6.24259726e-07
    6.24259726e-07   2.55311067e-06  -1.77230926e-06   1.77230926e-06]
 [ -4.23071349e-04   2.67897488e-04  -1.06040939e-02   3.26513150e-02
    1.52640977e-03   6.92864582e-01   3.32600510e-04   7.20247163e-01
    3.55782948e-04  -5.05401522e-04   4.89064153e-04   1.63373685e-05
    3.48493664e-04  -6.95951354e-06  -3.41534151e-04   1.57344901e-04
   -1.57344901e-04  -1.77115914e-04   1.77115914e-04   3.19594394e-04
   -3.19594394e-04  -4.86888251e-04   1.31665149e-04  -1.31665149e-04]
 [ -3.67674483e-03  -7.88107586e-05   9.92240317e-01  -1.08557251e-01
   -2.98167264e

### Feature Importance with Extra Tree
Bagged decision trees like Random Forest and Extra Trees can be used to estimate the importance
of features. In the example below we construct a ExtraTreesClassifier classier for the Pima
Indians onset of diabetes dataset. You can learn more about the ExtraTreesClassifier class5
in the scikit-learn API.

In [94]:
from sklearn.ensemble import ExtraTreesClassifier
model = ExtraTreesClassifier()
model.fit(x, y)
print(model.feature_importances_)
px2 = (model.feature_importances_)

[  4.74920509e-02   2.75551088e-02   1.27101376e-02   9.44423403e-03
   1.02681512e-02   1.38895808e-02   5.06453608e-03   1.07125375e-02
   5.93158189e-03   4.02841556e-02   1.89452724e-02   3.01616910e-05
   7.24070644e-03   1.69596667e-02   3.71723761e-03   6.63490258e-03
   1.70938361e-02   7.11089982e-03   4.82140717e-03   1.16757423e-02
   4.95542696e-03   7.08618513e-01   4.19397407e-03   4.65017909e-03]


In [95]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2066 entries, 0 to 2065
Data columns (total 25 columns):
Churn                                        2066 non-null float64
Children                                     2066 non-null float64
Est Income                                   2066 non-null float64
Age                                          2066 non-null float64
LongDistance                                 2066 non-null float64
International                                2066 non-null float64
Local                                        2066 non-null float64
Dropped                                      2066 non-null float64
Usage                                        2066 non-null float64
RatePlan                                     2066 non-null float64
Status_value_M                               2066 non-null float64
Status_value_S                               2066 non-null float64
Status_value_D                               2066 non-null float64
Paymethod_value_CC    

In [101]:
df4 = pd.DataFrame(px2)
df4.sort_values('Predictor Importance')
df4.rename(index={0:'Children',1:'Est Income',2:'Age'}, columns={0:'Predictor Importance'}, inplace=True)
df4
#Top Three Important Factors to predict Churn

Predictor Importance
Children                0.047492
Est Income              0.027555
Age                     0.012710
3                       0.009444
4                       0.010268
5                       0.013890
6                       0.005065
7                       0.010713
8                       0.005932
9                       0.040284
10                      0.018945
11                      0.000030
12                      0.007241
13                      0.016960
14                      0.003717
15                      0.006635
16                      0.017094
17                      0.007111
18                      0.004821
19                      0.011676
20                      0.004955
21                      0.708619
22                      0.004194
23                      0.004650

### Simple Logistic Regression with Train_Test_Split

In [102]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [109]:
test_size = 0.33
seed = 23
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = test_size, random_state = seed)
model = LogisticRegression()
model.fit(x_train, y_train)
result = model.score(x_test, y_test)
result


0.96334310850439886

### K-fold Cross-Validation
Cross-validation is an approach that you can use to estimate the performance of a machine
learning algorithm with less variance than a single train-test set split. It works by splitting
the dataset into k-parts (e.g. k = 5 or k = 10). Each split of the data is called a fold. The
algorithm is trained on k 􀀀 1 folds with one held back and tested on the held back fold. This is
repeated so that each fold of the dataset is given a chance to be the held back test set. After
running cross-validation you end up with k dierent performance scores that you can summarize
using a mean and a standard deviation.
The result is a more reliable estimate of the performance of the algorithm on new data. It is
more accurate because the algorithm is trained and evaluated multiple times on dierent data.
The choice of k must allow the size of each test partition to be large enough to be a reasonable
sample of the problem, whilst allowing enough repetitions of the train-test evaluation of the
algorithm to provide a fair estimate of the algorithms performance on unseen data. For modest
sized datasets in the thousands or tens of thousands of records, k values of 3, 5 and 10 are
common. In the example below we use 10-fold cross-validation.

In [110]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [113]:
num_folds = 10
seed = 7
kfold = KFold(n_splits=num_folds, random_state=seed)
model = LogisticRegression()
results = cross_val_score(model, x, y, cv=kfold)
results

array([ 1.        ,  0.96618357,  1.        ,  1.        ,  0.98067633,
        0.96135266,  1.        ,  1.        ,  0.99514563,  0.99514563])

### K-fold Variation: Leave One Out
You can congure cross-validation so that the size of the fold is 1 (k is set to the number of
observations in your dataset). This variation of cross-validation is called leave-one-out cross-
validation. The result is a large number of performance measures that can be summarized
9.5. Repeated Random Test-Train Splits 60
in an eort to give a more reasonable estimate of the accuracy of your model on unseen
data. A downside is that it can be a computationally more expensive procedure than k-fold
cross-validation. In the example below we use leave-one-out cross-validation.

In [114]:
from sklearn.model_selection import LeaveOneOut

In [116]:
loocv = LeaveOneOut()
model = LogisticRegression()
results = cross_val_score(model, x, y, cv=loocv)
print("Accuracy: %.3f%% (%.3f%%)" % (results.mean()*100.0, results.std()*100.0))

Accuracy: 97.289% (16.239%)
